[workspace]
resolver = "3"
members = ["crates/headgate-core", "crates/headgate-postgres", "crates/headgate", "crates/headgate-proto", "crates/headgate-macros", "crates/headgate-api", "crates/headgate-redis", "crates/headgate-testkit", "crates/headgate-mysql", "crates/headgate-ui", "crates/headgate-migrate", "crates/headgate-shared", "crates/headgate-sql", "crates/headgate-workflow", "crates/headgate-crypto", "crates/headgate-otel", "examples/rust"]

[workspace.package]
version = "0.1.5"
edition = "2024"
authors = ["The headgate Authors"]
description = "A policy-aware distributed job queue with PostgreSQL, MySQL, and Redis backends."
homepage = "https://github.com/mujhtech/headgate"
repository = "https://github.com/mujhtech/headgate"
documentation = "https://headgate.mintlify.app"
readme = "README.md"
keywords = ["job-queue", "distributed-systems", "postgresql", "redis", "mysql"]
categories = ["asynchronous", "database"]
license = "Apache-2.0"

[workspace.dependencies]
async-trait = "0.1"
sha2 = "0.10"
headgate = { version = "0.1.5", path = "crates/headgate" }
headgate-core = { version = "0.1.5", path = "crates/headgate-core" }
headgate-macros = { version = "0.1.5", path = "crates/headgate-macros" }
headgate-migrate = { version = "0.1.5", path = "crates/headgate-migrate" }
headgate-mysql = { version = "0.1.5", path = "crates/headgate-mysql" }
headgate-postgres = { version = "0.1.5", path = "crates/headgate-postgres" }
headgate-redis = { version = "0.1.5", path = "crates/headgate-redis" }
headgate-shared = { version = "0.1.5", path = "crates/headgate-shared" }
headgate-sql = { version = "0.1.5", path = "crates/headgate-sql" }
headgate-testkit = { version = "0.1.5", path = "crates/headgate-testkit" }
headgate-ui = { version = "0.1.5", path = "crates/headgate-ui" }
headgate-otel = { version = "0.1.5", path = "crates/headgate-otel" }
