/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleJobsRouteImport } from './routes/_console.jobs'
import { Route as ConsolePeriodicRouteImport } from './routes/_console.periodic'
import { Route as ConsoleQuarantineRouteImport } from './routes/_console.quarantine'
import { Route as ConsoleQueuesRouteImport } from './routes/_console.queues'
import { Route as ConsoleRateClassesRouteImport } from './routes/_console.rate-classes'
import { Route as ConsoleWorkersRouteImport } from './routes/_console.workers'
import { Route as ConsoleWorkflowsRouteImport } from './routes/_console.workflows'
import { Route as ConsoleJobsJobIdRouteImport } from './routes/_console.jobs.$jobId'
import { Route as ConsoleWorkflowsWorkflowIdRouteImport } from './routes/_console.workflows_.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleJobsRoute = ConsoleJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePeriodicRoute = ConsolePeriodicRouteImport.update({
  id: '/periodic',
  path: '/periodic',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleQuarantineRoute = ConsoleQuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleQueuesRoute = ConsoleQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRateClassesRoute = ConsoleRateClassesRouteImport.update({
  id: '/rate-classes',
  path: '/rate-classes',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkersRoute = ConsoleWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkflowsRoute = ConsoleWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleJobsJobIdRoute = ConsoleJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ConsoleJobsRoute,
} as any)
const ConsoleWorkflowsWorkflowIdRoute =
  ConsoleWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows_/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof ConsoleJobsRouteWithChildren
  '/periodic': typeof ConsolePeriodicRoute
  '/quarantine': typeof ConsoleQuarantineRoute
  '/queues': typeof ConsoleQueuesRoute
  '/rate-classes': typeof ConsoleRateClassesRoute
  '/workers': typeof ConsoleWorkersRoute
  '/workflows': typeof ConsoleWorkflowsRoute
  '/jobs/$jobId': typeof ConsoleJobsJobIdRoute
  '/workflows/$workflowId': typeof ConsoleWorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof ConsoleJobsRouteWithChildren
  '/periodic': typeof ConsolePeriodicRoute
  '/quarantine': typeof ConsoleQuarantineRoute
  '/queues': typeof ConsoleQueuesRoute
  '/rate-classes': typeof ConsoleRateClassesRoute
  '/workers': typeof ConsoleWorkersRoute
  '/workflows': typeof ConsoleWorkflowsRoute
  '/jobs/$jobId': typeof ConsoleJobsJobIdRoute
  '/workflows/$workflowId': typeof ConsoleWorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/jobs': typeof ConsoleJobsRouteWithChildren
  '/_console/periodic': typeof ConsolePeriodicRoute
  '/_console/quarantine': typeof ConsoleQuarantineRoute
  '/_console/queues': typeof ConsoleQueuesRoute
  '/_console/rate-classes': typeof ConsoleRateClassesRoute
  '/_console/workers': typeof ConsoleWorkersRoute
  '/_console/workflows': typeof ConsoleWorkflowsRoute
  '/_console/jobs/$jobId': typeof ConsoleJobsJobIdRoute
  '/_console/workflows_/$workflowId': typeof ConsoleWorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/periodic'
    | '/quarantine'
    | '/queues'
    | '/rate-classes'
    | '/workers'
    | '/workflows'
    | '/jobs/$jobId'
    | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/periodic'
    | '/quarantine'
    | '/queues'
    | '/rate-classes'
    | '/workers'
    | '/workflows'
    | '/jobs/$jobId'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/_console/jobs'
    | '/_console/periodic'
    | '/_console/quarantine'
    | '/_console/queues'
    | '/_console/rate-classes'
    | '/_console/workers'
    | '/_console/workflows'
    | '/_console/jobs/$jobId'
    | '/_console/workflows_/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/jobs': {
      id: '/_console/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ConsoleJobsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/periodic': {
      id: '/_console/periodic'
      path: '/periodic'
      fullPath: '/periodic'
      preLoaderRoute: typeof ConsolePeriodicRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/quarantine': {
      id: '/_console/quarantine'
      path: '/quarantine'
      fullPath: '/quarantine'
      preLoaderRoute: typeof ConsoleQuarantineRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/queues': {
      id: '/_console/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof ConsoleQueuesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/rate-classes': {
      id: '/_console/rate-classes'
      path: '/rate-classes'
      fullPath: '/rate-classes'
      preLoaderRoute: typeof ConsoleRateClassesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/workers': {
      id: '/_console/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof ConsoleWorkersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/workflows': {
      id: '/_console/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ConsoleWorkflowsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/jobs/$jobId': {
      id: '/_console/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof ConsoleJobsJobIdRouteImport
      parentRoute: typeof ConsoleJobsRoute
    }
    '/_console/workflows_/$workflowId': {
      id: '/_console/workflows_/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof ConsoleWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleJobsRouteChildren {
  ConsoleJobsJobIdRoute: typeof ConsoleJobsJobIdRoute
}

const ConsoleJobsRouteChildren: ConsoleJobsRouteChildren = {
  ConsoleJobsJobIdRoute: ConsoleJobsJobIdRoute,
}

const ConsoleJobsRouteWithChildren = ConsoleJobsRoute._addFileChildren(
  ConsoleJobsRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleJobsRoute: typeof ConsoleJobsRouteWithChildren
  ConsolePeriodicRoute: typeof ConsolePeriodicRoute
  ConsoleQuarantineRoute: typeof ConsoleQuarantineRoute
  ConsoleQueuesRoute: typeof ConsoleQueuesRoute
  ConsoleRateClassesRoute: typeof ConsoleRateClassesRoute
  ConsoleWorkersRoute: typeof ConsoleWorkersRoute
  ConsoleWorkflowsRoute: typeof ConsoleWorkflowsRoute
  ConsoleWorkflowsWorkflowIdRoute: typeof ConsoleWorkflowsWorkflowIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleJobsRoute: ConsoleJobsRouteWithChildren,
  ConsolePeriodicRoute: ConsolePeriodicRoute,
  ConsoleQuarantineRoute: ConsoleQuarantineRoute,
  ConsoleQueuesRoute: ConsoleQueuesRoute,
  ConsoleRateClassesRoute: ConsoleRateClassesRoute,
  ConsoleWorkersRoute: ConsoleWorkersRoute,
  ConsoleWorkflowsRoute: ConsoleWorkflowsRoute,
  ConsoleWorkflowsWorkflowIdRoute: ConsoleWorkflowsWorkflowIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
