// Code generated by protoc-gen-go. DO NOT EDIT.
// source: headgate.proto

package headgatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// lifecycle state machine The state machine is a declared table, not a match with holes.
type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_SCHEDULED   State = 1  // scheduled_at in the future
	State_STATE_AVAILABLE   State = 2  // ready to be admitted
	State_STATE_RUNNING     State = 3  // claimed, lease held
	State_STATE_RETRYABLE   State = 4  // failed, will return to AVAILABLE
	State_STATE_COMPLETED   State = 5  // terminal, retained per policy
	State_STATE_ARCHIVED    State = 6  // terminal, inspectable, re-runnable (the DLQ)
	State_STATE_CANCELLED   State = 7  // terminal, operator action
	State_STATE_QUARANTINED State = 8  // crash quarantine terminal, fingerprint blocked
	State_STATE_UNDECODABLE State = 9  // payload versioning terminal, no upcast path for this schema_version
	State_STATE_PENDING     State = 10 // durable but ineligible until explicit promotion
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0:  "STATE_UNSPECIFIED",
		1:  "STATE_SCHEDULED",
		2:  "STATE_AVAILABLE",
		3:  "STATE_RUNNING",
		4:  "STATE_RETRYABLE",
		5:  "STATE_COMPLETED",
		6:  "STATE_ARCHIVED",
		7:  "STATE_CANCELLED",
		8:  "STATE_QUARANTINED",
		9:  "STATE_UNDECODABLE",
		10: "STATE_PENDING",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_SCHEDULED":   1,
		"STATE_AVAILABLE":   2,
		"STATE_RUNNING":     3,
		"STATE_RETRYABLE":   4,
		"STATE_COMPLETED":   5,
		"STATE_ARCHIVED":    6,
		"STATE_CANCELLED":   7,
		"STATE_QUARANTINED": 8,
		"STATE_UNDECODABLE": 9,
		"STATE_PENDING":     10,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_headgate_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_headgate_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{0}
}

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED  Outcome = 0
	Outcome_OUTCOME_SUCCESS      Outcome = 1
	Outcome_OUTCOME_RETRY        Outcome = 2 // handler returned an error
	Outcome_OUTCOME_SKIP         Outcome = 3 // handler said: stop retrying, archive
	Outcome_OUTCOME_REVOKE       Outcome = 4 // handler said: drop entirely
	Outcome_OUTCOME_SNOOZE       Outcome = 5 // reschedule without consuming an attempt
	Outcome_OUTCOME_LEASE_LOST   Outcome = 6 // crash quarantine crash-attributed: worker died, never acked
	Outcome_OUTCOME_UNDECODABLE  Outcome = 7 // payload versioning payload could not be decoded
	Outcome_OUTCOME_RATE_LIMITED Outcome = 8 // surveyed policy behavior NOT a failure: re-queue without consuming an attempt
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCESS",
		2: "OUTCOME_RETRY",
		3: "OUTCOME_SKIP",
		4: "OUTCOME_REVOKE",
		5: "OUTCOME_SNOOZE",
		6: "OUTCOME_LEASE_LOST",
		7: "OUTCOME_UNDECODABLE",
		8: "OUTCOME_RATE_LIMITED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":  0,
		"OUTCOME_SUCCESS":      1,
		"OUTCOME_RETRY":        2,
		"OUTCOME_SKIP":         3,
		"OUTCOME_REVOKE":       4,
		"OUTCOME_SNOOZE":       5,
		"OUTCOME_LEASE_LOST":   6,
		"OUTCOME_UNDECODABLE":  7,
		"OUTCOME_RATE_LIMITED": 8,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_headgate_proto_enumTypes[1].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_headgate_proto_enumTypes[1]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{1}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // ULID: lexicographically sortable, no coordination
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                         // task type name; the dispatch key
	SchemaVersion uint32                 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // payload versioning payload versioning — free now, impossible later
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                   // opaque to headgate; codec is the caller's choice
	Queue         string                 `protobuf:"bytes,5,opt,name=queue,proto3" json:"queue,omitempty"`
	PartitionKey  string                 `protobuf:"bytes,6,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`   // tenant fairness fair queuing (tenant/customer). "" = default partition
	RateClass     string                 `protobuf:"bytes,7,opt,name=rate_class,json=rateClass,proto3" json:"rate_class,omitempty"`            // admission policy fleet-wide limiter bucket. "" = unlimited
	Fingerprint   string                 `protobuf:"bytes,8,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                         // crash quarantine quarantine key: hash(kind, payload)
	Attempt       uint32                 `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`                                // failures the handler RETURNED
	CrashAttempt  uint32                 `protobuf:"varint,10,opt,name=crash_attempt,json=crashAttempt,proto3" json:"crash_attempt,omitempty"` // crash quarantine failures where the worker DIED. counted separately.
	MaxAttempts   uint32                 `protobuf:"varint,11,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Priority      int32                  `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`                               // higher runs first within a queue
	EnqueuedAtMs  int64                  `protobuf:"varint,13,opt,name=enqueued_at_ms,json=enqueuedAtMs,proto3" json:"enqueued_at_ms,omitempty"` // wire-time contract every duration and instant is milliseconds
	ScheduledAtMs int64                  `protobuf:"varint,14,opt,name=scheduled_at_ms,json=scheduledAtMs,proto3" json:"scheduled_at_ms,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,15,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // per attempt
	DeadlineMs    int64                  `protobuf:"varint,16,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"` // absolute, across all attempts. 0 = none
	RetentionMs   int64                  `protobuf:"varint,17,opt,name=retention_ms,json=retentionMs,proto3" json:"retention_ms,omitempty"`
	UniqueKey     []byte                 `protobuf:"bytes,18,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`           // job uniqueness null = not unique
	UniqueStates  uint32                 `protobuf:"varint,19,opt,name=unique_states,json=uniqueStates,proto3" json:"unique_states,omitempty"` // bitmask of States uniqueness applies in
	Headers       map[string]string      `protobuf:"bytes,20,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Errors        []*AttemptError        `protobuf:"bytes,21,rep,name=errors,proto3" json:"errors,omitempty"`
	// job uniqueness uniqueness mode. 0 = LIFECYCLE (one live job per key, released by terminal
	// state). > 0 = THROTTLE (at most one per this many ms, released by the clock).
	UniqueWindowMs int64       `protobuf:"varint,22,opt,name=unique_window_ms,json=uniqueWindowMs,proto3" json:"unique_window_ms,omitempty"`
	Checkpoint     *Checkpoint `protobuf:"bytes,23,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"` // step replay step replay
	// surveyed policy behavior estimated rate-budget cost. This is NOT queue-selection weight. Proto3's
	// omitted zero is normalized to the default 1 by every store; an ack may report an
	// actual value (including zero) and atomically reconcile the estimate.
	Weight uint32 `protobuf:"varint,24,opt,name=weight,proto3" json:"weight,omitempty"`
	// Typed durable periodic origin. Empty/zero means an ordinary enqueue; both fields
	// are set together so clients never parse ids or opaque headers.
	PeriodicScheduleId string `protobuf:"bytes,25,opt,name=periodic_schedule_id,json=periodicScheduleId,proto3" json:"periodic_schedule_id,omitempty"`
	PeriodicTickMs     int64  `protobuf:"varint,26,opt,name=periodic_tick_ms,json=periodicTickMs,proto3" json:"periodic_tick_ms,omitempty"`
	// Request-only bitmask for atomic replacement on a unique-key conflict. Allowed
	// fields are defined by the language SDK constants; unknown bits are rejected.
	UniqueReplace uint32 `protobuf:"varint,27,opt,name=unique_replace,json=uniqueReplace,proto3" json:"unique_replace,omitempty"`
	// Trailing-edge debounce. Requires unique_key and a positive millisecond window.
	// The store schedules the holder at store-now + this window on both the first insert
	// and every conflict; it never trusts a producer clock.
	UniqueDebounceMs int64 `protobuf:"varint,28,opt,name=unique_debounce_ms,json=uniqueDebounceMs,proto3" json:"unique_debounce_ms,omitempty"`
	// River-compatible uniqueness scope. false includes kind in the effective key;
	// true deliberately coalesces equal keys across task kinds.
	UniqueExcludeKind bool `protobuf:"varint,29,opt,name=unique_exclude_kind,json=uniqueExcludeKind,proto3" json:"unique_exclude_kind,omitempty"`
	// Operator-indexed labels. Canonicalized by SDKs; never smuggled through headers.
	Tags []string `protobuf:"bytes,30,rep,name=tags,proto3" json:"tags,omitempty"`
	// Insert durably without becoming admission-eligible until explicitly promoted.
	Pending bool `protobuf:"varint,31,opt,name=pending,proto3" json:"pending,omitempty"`
	// Exact stable worker identity allowed to claim this job. Empty means any worker.
	// Enforced atomically by the store and retained across retry/reclaim transitions.
	StickyWorker  string `protobuf:"bytes,32,opt,name=sticky_worker,json=stickyWorker,proto3" json:"sticky_worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_headgate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Envelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Envelope) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *Envelope) GetRateClass() string {
	if x != nil {
		return x.RateClass
	}
	return ""
}

func (x *Envelope) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Envelope) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Envelope) GetCrashAttempt() uint32 {
	if x != nil {
		return x.CrashAttempt
	}
	return 0
}

func (x *Envelope) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Envelope) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Envelope) GetEnqueuedAtMs() int64 {
	if x != nil {
		return x.EnqueuedAtMs
	}
	return 0
}

func (x *Envelope) GetScheduledAtMs() int64 {
	if x != nil {
		return x.ScheduledAtMs
	}
	return 0
}

func (x *Envelope) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Envelope) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *Envelope) GetRetentionMs() int64 {
	if x != nil {
		return x.RetentionMs
	}
	return 0
}

func (x *Envelope) GetUniqueKey() []byte {
	if x != nil {
		return x.UniqueKey
	}
	return nil
}

func (x *Envelope) GetUniqueStates() uint32 {
	if x != nil {
		return x.UniqueStates
	}
	return 0
}

func (x *Envelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Envelope) GetErrors() []*AttemptError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Envelope) GetUniqueWindowMs() int64 {
	if x != nil {
		return x.UniqueWindowMs
	}
	return 0
}

func (x *Envelope) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *Envelope) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Envelope) GetPeriodicScheduleId() string {
	if x != nil {
		return x.PeriodicScheduleId
	}
	return ""
}

func (x *Envelope) GetPeriodicTickMs() int64 {
	if x != nil {
		return x.PeriodicTickMs
	}
	return 0
}

func (x *Envelope) GetUniqueReplace() uint32 {
	if x != nil {
		return x.UniqueReplace
	}
	return 0
}

func (x *Envelope) GetUniqueDebounceMs() int64 {
	if x != nil {
		return x.UniqueDebounceMs
	}
	return 0
}

func (x *Envelope) GetUniqueExcludeKind() bool {
	if x != nil {
		return x.UniqueExcludeKind
	}
	return false
}

func (x *Envelope) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Envelope) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *Envelope) GetStickyWorker() string {
	if x != nil {
		return x.StickyWorker
	}
	return ""
}

// step replay Step replay. River persists this only after the worker returns, which loses it in
// exactly the mid-step crash the feature exists for; Sidekiq autosaves every 5s. Here the
// checkpoint rides the lease renewal that is already happening, so step boundaries are
// exact and cursor updates are bounded by the renewal interval.
type Checkpoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastCompletedStep string                 `protobuf:"bytes,1,opt,name=last_completed_step,json=lastCompletedStep,proto3" json:"last_completed_step,omitempty"`
	CursorStep        string                 `protobuf:"bytes,2,opt,name=cursor_step,json=cursorStep,proto3" json:"cursor_step,omitempty"` // the step a cursor belongs to, if any
	Cursor            []byte                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                           // opaque, caller-serialized
	UpdatedAtMs       int64                  `protobuf:"varint,4,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	// payload versioning × step replay: what the step set looked like when this was written. A resumed job whose
	// step set no longer matches goes to UNDECODABLE rather than silently restarting from
	// step one and re-running completed side effects. No other queue has to answer this,
	// because no other queue has both step replay and payload versioning.
	SchemaVersion uint32            `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	StepSetHash   string            `protobuf:"bytes,6,opt,name=step_set_hash,json=stepSetHash,proto3" json:"step_set_hash,omitempty"`
	CrashesByStep map[string]uint32 `protobuf:"bytes,7,rep,name=crashes_by_step,json=crashesByStep,proto3" json:"crashes_by_step,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // crash quarantine step-level crash attribution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_headgate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{1}
}

func (x *Checkpoint) GetLastCompletedStep() string {
	if x != nil {
		return x.LastCompletedStep
	}
	return ""
}

func (x *Checkpoint) GetCursorStep() string {
	if x != nil {
		return x.CursorStep
	}
	return ""
}

func (x *Checkpoint) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Checkpoint) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *Checkpoint) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Checkpoint) GetStepSetHash() string {
	if x != nil {
		return x.StepSetHash
	}
	return ""
}

func (x *Checkpoint) GetCrashesByStep() map[string]uint32 {
	if x != nil {
		return x.CrashesByStep
	}
	return nil
}

type AttemptError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       uint32                 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	AtMs          int64                  `protobuf:"varint,2,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Outcome       Outcome                `protobuf:"varint,4,opt,name=outcome,proto3,enum=headgate.v1.Outcome" json:"outcome,omitempty"`
	WasPanic      bool                   `protobuf:"varint,5,opt,name=was_panic,json=wasPanic,proto3" json:"was_panic,omitempty"`
	Worker        string                 `protobuf:"bytes,6,opt,name=worker,proto3" json:"worker,omitempty"`
	Step          string                 `protobuf:"bytes,7,opt,name=step,proto3" json:"step,omitempty"` // step replay which step failed, when the job has steps
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptError) Reset() {
	*x = AttemptError{}
	mi := &file_headgate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptError) ProtoMessage() {}

func (x *AttemptError) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptError.ProtoReflect.Descriptor instead.
func (*AttemptError) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{2}
}

func (x *AttemptError) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AttemptError) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *AttemptError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AttemptError) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *AttemptError) GetWasPanic() bool {
	if x != nil {
		return x.WasPanic
	}
	return false
}

func (x *AttemptError) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *AttemptError) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

type Claim struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Envelope         *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	LeaseId          string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"` // lease fencing created atomically with the claim, never separately
	LeaseExpiresAtMs int64                  `protobuf:"varint,3,opt,name=lease_expires_at_ms,json=leaseExpiresAtMs,proto3" json:"lease_expires_at_ms,omitempty"`
	Fence            uint64                 `protobuf:"varint,4,opt,name=fence,proto3" json:"fence,omitempty"` // monotonic per job; rejects writes from a superseded holder
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_headgate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{3}
}

func (x *Claim) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *Claim) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Claim) GetLeaseExpiresAtMs() int64 {
	if x != nil {
		return x.LeaseExpiresAtMs
	}
	return 0
}

func (x *Claim) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

type WorkerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Pid            int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Queues         []string               `protobuf:"bytes,5,rep,name=queues,proto3" json:"queues,omitempty"`
	Concurrency    uint32                 `protobuf:"varint,6,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	StartedAtMs    int64                  `protobuf:"varint,7,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	HeartbeatAtMs  int64                  `protobuf:"varint,8,opt,name=heartbeat_at_ms,json=heartbeatAtMs,proto3" json:"heartbeat_at_ms,omitempty"`
	Inflight       uint32                 `protobuf:"varint,9,opt,name=inflight,proto3" json:"inflight,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DutiesActive   bool                   `protobuf:"varint,11,opt,name=duties_active,json=dutiesActive,proto3" json:"duties_active,omitempty"`
	PendingCommand string                 `protobuf:"bytes,12,opt,name=pending_command,json=pendingCommand,proto3" json:"pending_command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_headgate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *WorkerInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkerInfo) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *WorkerInfo) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *WorkerInfo) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *WorkerInfo) GetHeartbeatAtMs() int64 {
	if x != nil {
		return x.HeartbeatAtMs
	}
	return 0
}

func (x *WorkerInfo) GetInflight() uint32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetDutiesActive() bool {
	if x != nil {
		return x.DutiesActive
	}
	return false
}

func (x *WorkerInfo) GetPendingCommand() string {
	if x != nil {
		return x.PendingCommand
	}
	return ""
}

// admission policy Admission policy, evaluated store-side inside the claim.
type RateClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // tokens per window
	WindowMs      int64                  `protobuf:"varint,3,opt,name=window_ms,json=windowMs,proto3" json:"window_ms,omitempty"`
	Burst         uint64                 `protobuf:"varint,4,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateClass) Reset() {
	*x = RateClass{}
	mi := &file_headgate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateClass) ProtoMessage() {}

func (x *RateClass) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateClass.ProtoReflect.Descriptor instead.
func (*RateClass) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{5}
}

func (x *RateClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateClass) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateClass) GetWindowMs() int64 {
	if x != nil {
		return x.WindowMs
	}
	return 0
}

func (x *RateClass) GetBurst() uint64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type ConcurrencyLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PartitionBy   string                 `protobuf:"bytes,2,opt,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"` // "" = global, else an envelope field name
	MaxConcurrent uint64                 `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Queue         string                 `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	OnSaturated   string                 `protobuf:"bytes,5,opt,name=on_saturated,json=onSaturated,proto3" json:"on_saturated,omitempty"` // queue|discard|cancel_running|cancel_incoming
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrencyLimit) Reset() {
	*x = ConcurrencyLimit{}
	mi := &file_headgate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencyLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencyLimit) ProtoMessage() {}

func (x *ConcurrencyLimit) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencyLimit.ProtoReflect.Descriptor instead.
func (*ConcurrencyLimit) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{6}
}

func (x *ConcurrencyLimit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConcurrencyLimit) GetPartitionBy() string {
	if x != nil {
		return x.PartitionBy
	}
	return ""
}

func (x *ConcurrencyLimit) GetMaxConcurrent() uint64 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *ConcurrencyLimit) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ConcurrencyLimit) GetOnSaturated() string {
	if x != nil {
		return x.OnSaturated
	}
	return ""
}

// backlog metrics Backlog derivatives — a read, not a Prometheus recording rule.
type QueueStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Queue              string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	ByState            map[string]uint64      `protobuf:"bytes,2,rep,name=by_state,json=byState,proto3" json:"by_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ArrivalRate        float64                `protobuf:"fixed64,3,opt,name=arrival_rate,json=arrivalRate,proto3" json:"arrival_rate,omitempty"`          // jobs/sec, 1m window
	DrainRate          float64                `protobuf:"fixed64,4,opt,name=drain_rate,json=drainRate,proto3" json:"drain_rate,omitempty"`                // jobs/sec, 1m window
	TimeToDrainMs      int64                  `protobuf:"varint,5,opt,name=time_to_drain_ms,json=timeToDrainMs,proto3" json:"time_to_drain_ms,omitempty"` // -1 when arrival >= drain: the alert condition
	Paused             bool                   `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	CountIsApproximate bool                   `protobuf:"varint,7,opt,name=count_is_approximate,json=countIsApproximate,proto3" json:"count_is_approximate,omitempty"` // bounded live-control contract true when a bound was hit
	OldestAvailableMs  int64                  `protobuf:"varint,8,opt,name=oldest_available_ms,json=oldestAvailableMs,proto3" json:"oldest_available_ms,omitempty"`    // -1 when no job is currently available
	QuietGroups        *QuietGroupMetrics     `protobuf:"bytes,9,opt,name=quiet_groups,json=quietGroups,proto3" json:"quiet_groups,omitempty"`
	Weight             uint32                 `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`                                                        // queue-selection weight; unrelated to Envelope.weight
	UnfinishedJobs     uint64                 `protobuf:"varint,11,opt,name=unfinished_jobs,json=unfinishedJobs,proto3" json:"unfinished_jobs,omitempty"`                  // exact producer-depth counter, never approximate
	MaxUnfinishedJobs  *uint64                `protobuf:"varint,12,opt,name=max_unfinished_jobs,json=maxUnfinishedJobs,proto3,oneof" json:"max_unfinished_jobs,omitempty"` // absent = enqueue backpressure disabled
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueueStats) Reset() {
	*x = QueueStats{}
	mi := &file_headgate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStats) ProtoMessage() {}

func (x *QueueStats) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStats.ProtoReflect.Descriptor instead.
func (*QueueStats) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{7}
}

func (x *QueueStats) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueStats) GetByState() map[string]uint64 {
	if x != nil {
		return x.ByState
	}
	return nil
}

func (x *QueueStats) GetArrivalRate() float64 {
	if x != nil {
		return x.ArrivalRate
	}
	return 0
}

func (x *QueueStats) GetDrainRate() float64 {
	if x != nil {
		return x.DrainRate
	}
	return 0
}

func (x *QueueStats) GetTimeToDrainMs() int64 {
	if x != nil {
		return x.TimeToDrainMs
	}
	return 0
}

func (x *QueueStats) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *QueueStats) GetCountIsApproximate() bool {
	if x != nil {
		return x.CountIsApproximate
	}
	return false
}

func (x *QueueStats) GetOldestAvailableMs() int64 {
	if x != nil {
		return x.OldestAvailableMs
	}
	return 0
}

func (x *QueueStats) GetQuietGroups() *QuietGroupMetrics {
	if x != nil {
		return x.QuietGroups
	}
	return nil
}

func (x *QueueStats) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *QueueStats) GetUnfinishedJobs() uint64 {
	if x != nil {
		return x.UnfinishedJobs
	}
	return 0
}

func (x *QueueStats) GetMaxUnfinishedJobs() uint64 {
	if x != nil && x.MaxUnfinishedJobs != nil {
		return *x.MaxUnfinishedJobs
	}
	return 0
}

type QuietGroupMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArrivalRate       float64                `protobuf:"fixed64,1,opt,name=arrival_rate,json=arrivalRate,proto3" json:"arrival_rate,omitempty"`
	DrainRate         float64                `protobuf:"fixed64,2,opt,name=drain_rate,json=drainRate,proto3" json:"drain_rate,omitempty"`
	TimeToDrainMs     int64                  `protobuf:"varint,3,opt,name=time_to_drain_ms,json=timeToDrainMs,proto3" json:"time_to_drain_ms,omitempty"`           // -1 when arrival >= drain
	OldestAvailableMs int64                  `protobuf:"varint,4,opt,name=oldest_available_ms,json=oldestAvailableMs,proto3" json:"oldest_available_ms,omitempty"` // -1 when no quiet job is available
	NoisyPartitions   uint32                 `protobuf:"varint,5,opt,name=noisy_partitions,json=noisyPartitions,proto3" json:"noisy_partitions,omitempty"`
	Approximate       bool                   `protobuf:"varint,6,opt,name=approximate,proto3" json:"approximate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuietGroupMetrics) Reset() {
	*x = QuietGroupMetrics{}
	mi := &file_headgate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuietGroupMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuietGroupMetrics) ProtoMessage() {}

func (x *QuietGroupMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_headgate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuietGroupMetrics.ProtoReflect.Descriptor instead.
func (*QuietGroupMetrics) Descriptor() ([]byte, []int) {
	return file_headgate_proto_rawDescGZIP(), []int{8}
}

func (x *QuietGroupMetrics) GetArrivalRate() float64 {
	if x != nil {
		return x.ArrivalRate
	}
	return 0
}

func (x *QuietGroupMetrics) GetDrainRate() float64 {
	if x != nil {
		return x.DrainRate
	}
	return 0
}

func (x *QuietGroupMetrics) GetTimeToDrainMs() int64 {
	if x != nil {
		return x.TimeToDrainMs
	}
	return 0
}

func (x *QuietGroupMetrics) GetOldestAvailableMs() int64 {
	if x != nil {
		return x.OldestAvailableMs
	}
	return 0
}

func (x *QuietGroupMetrics) GetNoisyPartitions() uint32 {
	if x != nil {
		return x.NoisyPartitions
	}
	return 0
}

func (x *QuietGroupMetrics) GetApproximate() bool {
	if x != nil {
		return x.Approximate
	}
	return false
}

var File_headgate_proto protoreflect.FileDescriptor

const file_headgate_proto_rawDesc = "" +
	"\n" +
	"\x0eheadgate.proto\x12\vheadgate.v1\"\xba\t\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\rR\rschemaVersion\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x14\n" +
	"\x05queue\x18\x05 \x01(\tR\x05queue\x12#\n" +
	"\rpartition_key\x18\x06 \x01(\tR\fpartitionKey\x12\x1d\n" +
	"\n" +
	"rate_class\x18\a \x01(\tR\trateClass\x12 \n" +
	"\vfingerprint\x18\b \x01(\tR\vfingerprint\x12\x18\n" +
	"\aattempt\x18\t \x01(\rR\aattempt\x12#\n" +
	"\rcrash_attempt\x18\n" +
	" \x01(\rR\fcrashAttempt\x12!\n" +
	"\fmax_attempts\x18\v \x01(\rR\vmaxAttempts\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x05R\bpriority\x12$\n" +
	"\x0eenqueued_at_ms\x18\r \x01(\x03R\fenqueuedAtMs\x12&\n" +
	"\x0fscheduled_at_ms\x18\x0e \x01(\x03R\rscheduledAtMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x0f \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vdeadline_ms\x18\x10 \x01(\x03R\n" +
	"deadlineMs\x12!\n" +
	"\fretention_ms\x18\x11 \x01(\x03R\vretentionMs\x12\x1d\n" +
	"\n" +
	"unique_key\x18\x12 \x01(\fR\tuniqueKey\x12#\n" +
	"\runique_states\x18\x13 \x01(\rR\funiqueStates\x12<\n" +
	"\aheaders\x18\x14 \x03(\v2\".headgate.v1.Envelope.HeadersEntryR\aheaders\x121\n" +
	"\x06errors\x18\x15 \x03(\v2\x19.headgate.v1.AttemptErrorR\x06errors\x12(\n" +
	"\x10unique_window_ms\x18\x16 \x01(\x03R\x0euniqueWindowMs\x127\n" +
	"\n" +
	"checkpoint\x18\x17 \x01(\v2\x17.headgate.v1.CheckpointR\n" +
	"checkpoint\x12\x16\n" +
	"\x06weight\x18\x18 \x01(\rR\x06weight\x120\n" +
	"\x14periodic_schedule_id\x18\x19 \x01(\tR\x12periodicScheduleId\x12(\n" +
	"\x10periodic_tick_ms\x18\x1a \x01(\x03R\x0eperiodicTickMs\x12%\n" +
	"\x0eunique_replace\x18\x1b \x01(\rR\runiqueReplace\x12,\n" +
	"\x12unique_debounce_ms\x18\x1c \x01(\x03R\x10uniqueDebounceMs\x12.\n" +
	"\x13unique_exclude_kind\x18\x1d \x01(\bR\x11uniqueExcludeKind\x12\x12\n" +
	"\x04tags\x18\x1e \x03(\tR\x04tags\x12\x18\n" +
	"\apending\x18\x1f \x01(\bR\apending\x12#\n" +
	"\rsticky_worker\x18  \x01(\tR\fstickyWorker\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x02\n" +
	"\n" +
	"Checkpoint\x12.\n" +
	"\x13last_completed_step\x18\x01 \x01(\tR\x11lastCompletedStep\x12\x1f\n" +
	"\vcursor_step\x18\x02 \x01(\tR\n" +
	"cursorStep\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\fR\x06cursor\x12\"\n" +
	"\rupdated_at_ms\x18\x04 \x01(\x03R\vupdatedAtMs\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\rR\rschemaVersion\x12\"\n" +
	"\rstep_set_hash\x18\x06 \x01(\tR\vstepSetHash\x12R\n" +
	"\x0fcrashes_by_step\x18\a \x03(\v2*.headgate.v1.Checkpoint.CrashesByStepEntryR\rcrashesByStep\x1a@\n" +
	"\x12CrashesByStepEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xd0\x01\n" +
	"\fAttemptError\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\rR\aattempt\x12\x13\n" +
	"\x05at_ms\x18\x02 \x01(\x03R\x04atMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x14.headgate.v1.OutcomeR\aoutcome\x12\x1b\n" +
	"\twas_panic\x18\x05 \x01(\bR\bwasPanic\x12\x16\n" +
	"\x06worker\x18\x06 \x01(\tR\x06worker\x12\x12\n" +
	"\x04step\x18\a \x01(\tR\x04step\"\x9a\x01\n" +
	"\x05Claim\x121\n" +
	"\benvelope\x18\x01 \x01(\v2\x15.headgate.v1.EnvelopeR\benvelope\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12-\n" +
	"\x13lease_expires_at_ms\x18\x03 \x01(\x03R\x10leaseExpiresAtMs\x12\x14\n" +
	"\x05fence\x18\x04 \x01(\x04R\x05fence\"\xf1\x02\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06queues\x18\x05 \x03(\tR\x06queues\x12 \n" +
	"\vconcurrency\x18\x06 \x01(\rR\vconcurrency\x12\"\n" +
	"\rstarted_at_ms\x18\a \x01(\x03R\vstartedAtMs\x12&\n" +
	"\x0fheartbeat_at_ms\x18\b \x01(\x03R\rheartbeatAtMs\x12\x1a\n" +
	"\binflight\x18\t \x01(\rR\binflight\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12#\n" +
	"\rduties_active\x18\v \x01(\bR\fdutiesActive\x12'\n" +
	"\x0fpending_command\x18\f \x01(\tR\x0ependingCommand\"h\n" +
	"\tRateClass\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x1b\n" +
	"\twindow_ms\x18\x03 \x01(\x03R\bwindowMs\x12\x14\n" +
	"\x05burst\x18\x04 \x01(\x04R\x05burst\"\xa9\x01\n" +
	"\x10ConcurrencyLimit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpartition_by\x18\x02 \x01(\tR\vpartitionBy\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x04R\rmaxConcurrent\x12\x14\n" +
	"\x05queue\x18\x04 \x01(\tR\x05queue\x12!\n" +
	"\fon_saturated\x18\x05 \x01(\tR\vonSaturated\"\xd5\x04\n" +
	"\n" +
	"QueueStats\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12?\n" +
	"\bby_state\x18\x02 \x03(\v2$.headgate.v1.QueueStats.ByStateEntryR\abyState\x12!\n" +
	"\farrival_rate\x18\x03 \x01(\x01R\varrivalRate\x12\x1d\n" +
	"\n" +
	"drain_rate\x18\x04 \x01(\x01R\tdrainRate\x12'\n" +
	"\x10time_to_drain_ms\x18\x05 \x01(\x03R\rtimeToDrainMs\x12\x16\n" +
	"\x06paused\x18\x06 \x01(\bR\x06paused\x120\n" +
	"\x14count_is_approximate\x18\a \x01(\bR\x12countIsApproximate\x12.\n" +
	"\x13oldest_available_ms\x18\b \x01(\x03R\x11oldestAvailableMs\x12A\n" +
	"\fquiet_groups\x18\t \x01(\v2\x1e.headgate.v1.QuietGroupMetricsR\vquietGroups\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\rR\x06weight\x12'\n" +
	"\x0funfinished_jobs\x18\v \x01(\x04R\x0eunfinishedJobs\x123\n" +
	"\x13max_unfinished_jobs\x18\f \x01(\x04H\x00R\x11maxUnfinishedJobs\x88\x01\x01\x1a:\n" +
	"\fByStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\x16\n" +
	"\x14_max_unfinished_jobs\"\xfb\x01\n" +
	"\x11QuietGroupMetrics\x12!\n" +
	"\farrival_rate\x18\x01 \x01(\x01R\varrivalRate\x12\x1d\n" +
	"\n" +
	"drain_rate\x18\x02 \x01(\x01R\tdrainRate\x12'\n" +
	"\x10time_to_drain_ms\x18\x03 \x01(\x03R\rtimeToDrainMs\x12.\n" +
	"\x13oldest_available_ms\x18\x04 \x01(\x03R\x11oldestAvailableMs\x12)\n" +
	"\x10noisy_partitions\x18\x05 \x01(\rR\x0fnoisyPartitions\x12 \n" +
	"\vapproximate\x18\x06 \x01(\bR\vapproximate*\xef\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATE_SCHEDULED\x10\x01\x12\x13\n" +
	"\x0fSTATE_AVAILABLE\x10\x02\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x03\x12\x13\n" +
	"\x0fSTATE_RETRYABLE\x10\x04\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x05\x12\x12\n" +
	"\x0eSTATE_ARCHIVED\x10\x06\x12\x13\n" +
	"\x0fSTATE_CANCELLED\x10\a\x12\x15\n" +
	"\x11STATE_QUARANTINED\x10\b\x12\x15\n" +
	"\x11STATE_UNDECODABLE\x10\t\x12\x11\n" +
	"\rSTATE_PENDING\x10\n" +
	"*\xcf\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_SUCCESS\x10\x01\x12\x11\n" +
	"\rOUTCOME_RETRY\x10\x02\x12\x10\n" +
	"\fOUTCOME_SKIP\x10\x03\x12\x12\n" +
	"\x0eOUTCOME_REVOKE\x10\x04\x12\x12\n" +
	"\x0eOUTCOME_SNOOZE\x10\x05\x12\x16\n" +
	"\x12OUTCOME_LEASE_LOST\x10\x06\x12\x17\n" +
	"\x13OUTCOME_UNDECODABLE\x10\a\x12\x18\n" +
	"\x14OUTCOME_RATE_LIMITED\x10\bB2Z0github.com/mujhtech/headgate/go/proto/headgatev1b\x06proto3"

var (
	file_headgate_proto_rawDescOnce sync.Once
	file_headgate_proto_rawDescData []byte
)

func file_headgate_proto_rawDescGZIP() []byte {
	file_headgate_proto_rawDescOnce.Do(func() {
		file_headgate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_headgate_proto_rawDesc), len(file_headgate_proto_rawDesc)))
	})
	return file_headgate_proto_rawDescData
}

var file_headgate_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_headgate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_headgate_proto_goTypes = []any{
	(State)(0),                // 0: headgate.v1.State
	(Outcome)(0),              // 1: headgate.v1.Outcome
	(*Envelope)(nil),          // 2: headgate.v1.Envelope
	(*Checkpoint)(nil),        // 3: headgate.v1.Checkpoint
	(*AttemptError)(nil),      // 4: headgate.v1.AttemptError
	(*Claim)(nil),             // 5: headgate.v1.Claim
	(*WorkerInfo)(nil),        // 6: headgate.v1.WorkerInfo
	(*RateClass)(nil),         // 7: headgate.v1.RateClass
	(*ConcurrencyLimit)(nil),  // 8: headgate.v1.ConcurrencyLimit
	(*QueueStats)(nil),        // 9: headgate.v1.QueueStats
	(*QuietGroupMetrics)(nil), // 10: headgate.v1.QuietGroupMetrics
	nil,                       // 11: headgate.v1.Envelope.HeadersEntry
	nil,                       // 12: headgate.v1.Checkpoint.CrashesByStepEntry
	nil,                       // 13: headgate.v1.QueueStats.ByStateEntry
}
var file_headgate_proto_depIdxs = []int32{
	11, // 0: headgate.v1.Envelope.headers:type_name -> headgate.v1.Envelope.HeadersEntry
	4,  // 1: headgate.v1.Envelope.errors:type_name -> headgate.v1.AttemptError
	3,  // 2: headgate.v1.Envelope.checkpoint:type_name -> headgate.v1.Checkpoint
	12, // 3: headgate.v1.Checkpoint.crashes_by_step:type_name -> headgate.v1.Checkpoint.CrashesByStepEntry
	1,  // 4: headgate.v1.AttemptError.outcome:type_name -> headgate.v1.Outcome
	2,  // 5: headgate.v1.Claim.envelope:type_name -> headgate.v1.Envelope
	13, // 6: headgate.v1.QueueStats.by_state:type_name -> headgate.v1.QueueStats.ByStateEntry
	10, // 7: headgate.v1.QueueStats.quiet_groups:type_name -> headgate.v1.QuietGroupMetrics
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_headgate_proto_init() }
func file_headgate_proto_init() {
	if File_headgate_proto != nil {
		return
	}
	file_headgate_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_headgate_proto_rawDesc), len(file_headgate_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_headgate_proto_goTypes,
		DependencyIndexes: file_headgate_proto_depIdxs,
		EnumInfos:         file_headgate_proto_enumTypes,
		MessageInfos:      file_headgate_proto_msgTypes,
	}.Build()
	File_headgate_proto = out.File
	file_headgate_proto_goTypes = nil
	file_headgate_proto_depIdxs = nil
}
