[package]
name = "headgate-workflow"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
headgate = { workspace = true }
headgate-core = { workspace = true }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cel = "0.14.4"

[dev-dependencies]
headgate-mysql = { workspace = true }
headgate-postgres = { workspace = true }
headgate-redis = { workspace = true }
headgate-testkit = { workspace = true }
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
